version: '3'

services:
  my_reverse_proxy:
    build:
      context: ./my-reverse-proxy
    image: teemukoivisto/my-reverse-proxy
    ports:
      - 9080:80
      - 9443:443
    restart: always
  my_react_bootstrap:
    build:
      context: ./my-react-bootstrap
    restart: always
  my_node_bootstrap:
    build:
      context: ./my-node-bootstrap
    ports:
      - 9600:8600 
    environment:
      NODE_ENV: production
      PORT: 8600
      LOG_LEVEL: info
      JWT_SECRET: verylongrandomstring
      DB_HOST: host.docker.internal
      DB_PORT: 5600
      DB_USER: pg-user
      DB_PASSWORD: my-pg-password
      DB_NAME: my_postgres_db
    restart: always
  my_flyway_migration:
    image: boxfuse/flyway:5.2.4-alpine
    entrypoint: ["sh", "-c", "/flyway/wait-for-it.sh my_postgres:5432 -- flyway migrate"]
    volumes:
    - ./my-node-bootstrap/db/migrations:/flyway/sql
    - ./my-node-bootstrap/db/seed/afterMigrate.sql:/flyway/sql/afterMigrate.sql # Should I do this automatically or use seed.sh..?
    - ./my-node-bootstrap/db/scripts/wait-for-it.sh:/flyway/wait-for-it.sh
    environment:
      FLYWAY_PASSWORD: my-pg-password
      FLYWAY_USER: pg-user
      FLYWAY_URL: jdbc:postgresql://my_postgres:5432/my_postgres_db
      FLYWAY_CONNECT_RETRIES: 180
  my_postgres:
    image: postgres:11.2-alpine
    ports:
      - 5600:5432
    environment:
      POSTGRES_PASSWORD: my-pg-password
      POSTGRES_USER: pg-user
      POSTGRES_DB: my_postgres_db
    restart: always
