# https://www.reddit.com/r/docker/comments/7fx9si/how_are_you_managing_db_migrations/
# https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
apiVersion: batch/v1
kind: Job
metadata:
  generateName: migration-
  labels:
    job: migration
spec:
  template:
    metadata:
      labels:
        job: migration
     spec:
      containers:
      - name: server
        image: XXXXXXXX.dkr.ecr.us-west-2.amazonaws.com/someCoolContainer:1.0
        command: ["./bin/migrate.js"]
