apiVersion: v1
kind: Service
metadata:
  name: my-postgres-svc
  labels:
    app: my-postgres
    project: example-kubernetes-stack
spec:
  ports:
  - port: 5432
  selector:
    app: my-postgres
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-postgres-deployment
  labels:
    app: my-postgres
    project: example-kubernetes-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-postgres
  template:
    metadata:
      labels:
        app: my-postgres
    spec:
      containers:
      - image: postgres:10.5
        name: my-postgres
        envFrom:
        - configMapRef:
            name: my-postgres-config
        env:
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-pg-password
              key: password
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim