# https://www.reddit.com/r/docker/comments/7fx9si/how_are_you_managing_db_migrations/
# https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
apiVersion: batch/v1
kind: Job
metadata:
  generateName: migration-
  labels:
    job: my-postgres-migration
    project: example-kubernetes-stack
spec:
  template:
    metadata:
      labels:
        job: my-postgres-migration
    spec:
      restartPolicy: Never
      containers:
      - name: my-postgres-migration
        image: boxfuse/flyway:5.2.4-alpine
        command: ["sh", "-c", "/flyway/wait-for-it.sh my_postgres:5432 -- flyway migrate"]
        env:
        - name: FLYWAY_URL
          value: "jdbc:postgresql://my_postgres:5432/my_postgres_db"
        - name: FLYWAY_USER
          value: "pg-user"
        - name: FLYWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-postgres-secret
              key: password
        - name: FLYWAY_CONNECT_RETRIES
          value: "180"

    volumes:
    - ./my-node-bootstrap/db/migrations:/flyway/sql
    - ./my-node-bootstrap/db/seed/afterMigrate.sql:/flyway/sql/afterMigrate.sql # Should I do this automatically or use seed.sh..?
    - ./my-node-bootstrap/db/scripts/wait-for-it.sh:/flyway/wait-for-it.sh