apiVersion: v1
kind: Secret
metadata:
  name: my-postgres-secret
  labels:
    app: my-postgres
    project: example-kubernetes-stack
type: Opaque
data:
  username: cGctdXNlcg== # pg-user
  password: YXNkZmFzZGY= # All the secrets are encoded in base64: echo -n 'asdfasdf' | base64