template_path: ecs-service.yaml
parameters:
  Environment: {{ command_path.0 }}
  Project: {{ project_code }}
  VpcId: !stack_output dev/eu-west-1/vpc.yaml::VpcId
  # Change to Public SNs if you don't want NAT (eg you don't need RDS)
  # and also "AssignPublicIp" inside the template to ENABLED
  1PrivateSubnetId: !stack_output dev/eu-west-1/vpc.yaml::1PrivateSubnetId
  2PrivateSubnetId: !stack_output dev/eu-west-1/vpc.yaml::2PrivateSubnetId
  3PrivateSubnetId: !stack_output dev/eu-west-1/vpc.yaml::3PrivateSubnetId
  AppSecurityGroupId: !stack_output dev/eu-west-1/security-groups.yaml::AppSecurityGroupId
  ECSClusterName: !stack_output dev/eu-west-1/ecs-cluster.yaml::ClusterName
  ScalingRoleArn: !stack_output dev/eu-west-1/ecs-cluster.yaml::ScalingRoleArn
  PublicTargetGroupArn: !stack_output dev/eu-west-1/ecs-cluster.yaml::PublicTargetGroupArn
  ExampleNodejsRepositoryUri: !stack_output dev/eu-west-1/ecr.yaml::ExampleNodejsRepositoryUri
  ServiceName: 'examplenodejs' # No dash (-) since mapping in ecs-service.yaml won't work otherwise
  ImageTag: 'latest' # Initial version, updated manually (with cloudformation update) by each new deployment
  ApplicationPort: '8600'
  DBName: !stack_output dev/eu-west-1/db.yaml::DBName
  DBURL: !stack_output dev/eu-west-1/db.yaml::DBURL
stack_tags:
  Environment: {{ command_path.0 }}
  Project: {{ project_code }}
