template_path: ecs-cluster.yaml
parameters:
  Environment: {{ command_path.0 }}
  Project: {{ project_code }}
  VpcId: !stack_output dev/eu-west-1/vpc.yaml::VpcId
  1PublicSubnetId: !stack_output dev/eu-west-1/vpc.yaml::1PublicSubnetId
  2PublicSubnetId: !stack_output dev/eu-west-1/vpc.yaml::2PublicSubnetId
  3PublicSubnetId: !stack_output dev/eu-west-1/vpc.yaml::3PublicSubnetId
  ALBSecurityGroupId: !stack_output dev/eu-west-1/security-groups.yaml::ALBSecurityGroupId
  ApplicationPort: '8600'
stack_tags:
  Environment: {{ command_path.0 }}
  Project: {{ project_code }}