template_path: vpc.yaml
parameters:
  Environment: {{ command_path.0 }}
  Project: {{ project_code }}
  CIDR: "10.10.0.0/16"
  PublicSubnet1CIDR: "10.10.0.0/20"
  PublicSubnet2CIDR: "10.10.16.0/20"
  PublicSubnet3CIDR: "10.10.32.0/20"
  PrivateSubnet1CIDR: "10.10.48.0/20"
  PrivateSubnet2CIDR: "10.10.64.0/20"
  PrivateSubnet3CIDR: "10.10.80.0/20"
stack_tags:
  Environment: {{ command_path.0 }}
  Project: {{ project_code }}
