template_path: vpc.yaml
parameters:
  Environment: {{ command_path.0 }}
  Project: {{ project_code }}
  CIDR: "10.10.0.0/16"
  1PublicSubnetCIDR: "10.10.0.0/20"
  2PublicSubnetCIDR: "10.10.16.0/20"
  3PublicSubnetCIDR: "10.10.32.0/20"
  1PrivateSubnetCIDR: "10.10.48.0/20"
  2PrivateSubnetCIDR: "10.10.64.0/20"
  3PrivateSubnetCIDR: "10.10.80.0/20"
stack_tags:
  Environment: {{ command_path.0 }}
  Project: {{ project_code }}
