AWSTemplateFormatVersion: 2010-09-09
Description: JWT secret & Postgres database credentials, created manually by uploading this template to AWS console

Parameters:
  Project:
    Description: Name of the project
    Type: String
    Default: example-app
  Environment:
    Description: Environment where the stack is launched
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  JWTSecret:
    Description: Secret for the application server JWT authentication. Min length 32
    Type: String
    MinLength: 32
    NoEcho: true
  DBUser:
    Description: Postgres root user. Min length 5
    Type: String
    MinLength: 5
    NoEcho: true
  DBPassword:
    Description: Postgres root password. Min length 32. Only printable ASCII characters besides '/', '@', '"', ' ' may be used
    Type: String
    MinLength: 32
    NoEcho: true
  CustomResourceExportName:
    Description: CF stack export name for the SSM-parameter custom resource Lambda ARN
    Type: String
    Default: example-app-dev-eu-west-1-custom-resource-ssm-parameter-Custom-Resource-Ssm-Parameter-Lambda-Arn

Resources:
  JWTSecretParameter:
    Type: Custom::EncryptedSsmParameter
    Properties:
      Description: Generated encrypted jwt-secret SSM parameter to be used in ECS-tasks
      Name: !Sub /${Project}/${Environment}/jwt-secret
      Value: !Ref JWTSecret
      ServiceToken:
        Fn::ImportValue: !Ref CustomResourceExportName
  DBUserParameter:
    Type: Custom::EncryptedSsmParameter
    Properties:
      Description: Generated encrypted db-user SSM parameter to be used in other stacks
      Name: !Sub /${Project}/${Environment}/db-user
      Value: !Ref DBUser
      ServiceToken:
        Fn::ImportValue: !Ref CustomResourceExportName
  DBPasswordParameter:
    Type: Custom::EncryptedSsmParameter
    Properties:
      Description: Generated encrypted db-password SSM parameter to be used in other stacks
      Name: !Sub /${Project}/${Environment}/db-password
      Value: !Ref DBPassword
      ServiceToken:
        Fn::ImportValue: !Ref CustomResourceExportName
